name: Validate Published Docker Image Tag

#on:
#  registry_package:
#    types: [published, updated, validate-image]
on:
  repository_dispatch:
    types: [validate-image]
    
  workflow_dispatch:
  
jobs:
  validate-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Dump event context
        run: echo "${{ toJSON(github.event) }}"
      - name: Validate image tag with github-script
        uses: actions/github-script@v7
        with:
          script: |
            const pkg = github.event.registry_package;
            const name = pkg.name; // ex: "app"
            const tag = pkg.package_version.container_metadata.tag.name; // ex: "v0.0.1"
            if (!tag.startsWith("v")) {
              core.setFailed(`Tag inválida: ${tag} (deveria começar com 'v')`);
            } else {
              core.info(`Tag válida detectada: ${tag} para pacote ${name}`);
            }
