name: Print Image Tag (multi-event)

on:
  registry_package:
    types: [published, updated]
  repository_dispatch:
    types: [validate-image]
  workflow_dispatch:

jobs:
  print-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          if [[ "${{ github.event_name }}" == "registry_package" ]]; then
            echo "Nome da imagem: ${{ github.event.registry_package.name }}"
            echo "Tag da imagem: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "Nome da imagem: app"
            echo "Tag da imagem: ${{ github.event.client_payload.image_tag }}"
          else
            echo "Evento não esperado para print de imagem/tag."
          fi
