name: Print Image Tag from registry_package

on:
  registry_package:
    types: [published, updated]

jobs:
  print-image-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Print image name and tag
        run: |
          echo "Nome da imagem: ${{ github.event.registry_package.name }}"
          echo "Tag da imagem: ${{ github.event.registry_package.package_version.container_metadata.tag.name }}"
